language: python
python:
  - "3.6"
  - "3.5"

# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script: nosetests

install:
- pip install python-coveralls
- pip install coverage
after_success: coveralls

