language: python
python:
  - "3.6"
  - "3.5"

# command to install dependencies
install: pip install -r requirements.txt
- pip3 install coverage
- pip3 install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package test
- coverage3 run tests/tests.py
- coverage3 report
- coveralls
after_success: coveralls


