language: python
python:
  - "3.6"
  - "3.5"

# command to install dependencies
install: pip install -r requirements.txt
- pip install nose coverage
- pip install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package test
after_success: coveralls




